# Generated by Django 3.1.7 on 2021-04-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('column', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
